author : henning1004
name: AddSomeFurniture
version: 0.9.0
main: me.henning1004.addsomefurniture.Main
commands:
   asf:
      description: Check if your AddSomeFurniture is up to date.
      usage: /<command>